---
title: "Premimum Bond Prize Finder"
format: 
  dashboard:
    scrolling: false
    theme: materia
    nav-buttons:
      - icon: github
        href: https://github.com/drclongstaff/premium_bonds
      - icon: bluesky
        href: http://bsky.app/profile/drclongstaff.bsky.social
      - icon: globe2
        href: https://drclongstaff.github.io/shiny-clots
      - text: Contact
        href: mailto:drclongstaff@gmail.com
server: shiny
---

```{r}
#| context: setup
library(ggplot2)
library(gt)
library(bslib)
library(data.table)
# Read once at startup, not on every input change
allMonths <- c("Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec")
#set up the pool for prize draws = 1 in 23000 zeros
prizePool <- rep(0, 23000)
x <- round(runif(1)*23000)
prizePool[x] <- 1
```


```{r}
#Month simulations
Earnest <- function(stake, pool, vals, probs){
  mywins <- sample(pool,stake, replace = TRUE)
  monthPrizes <- sum(mywins)
  monthWinnings <- sample(vals, monthPrizes, replace = TRUE,  prob = probs)
  monthTotal <- sum(monthWinnings)
  yearlyReturn <- (12*monthTotal/stake)*100
  
  # Collapse winnings into a readable string
  winningsStr <- if (length(monthWinnings) == 0) "0" else paste(sort(monthWinnings), collapse = ", ")
  results <- c(monthPrizes, monthTotal, yearlyReturn, winningsStr)
  
}

#Long term simulations
earnYear <- function(stake, pool, vals, probs){
  
  earnMonth <- function(stake, pool, vals, probs){
    mywins <- sample(pool,stake, replace = TRUE)
    monthPrizes <- sum(mywins)
    monthWinnings <- sample(vals, monthPrizes, replace = TRUE,  prob = probs)
    monthWin <- sum(monthWinnings)
  }
  
  Resmnth <- sapply(1:12, function(x) earnMonth(stake, pool, vals, probs))
  Resyrtotal <- sum(Resmnth)
}

```



#  {.sidebar}

#### Enter your premium bond number here

```{r}

 numericInput("simYrs", tags$b("Years of simulation"), "", 10, min = 5)

```

```{r}
tags$b("How many premium bonds to you hold (£)")
numericInput("bondStake", tags$b("Value of bonds"), "", 50000, min = 1)
tags$br()

```

```{r}
tags$b("Summary of returns")
#actionButton("go", "Refresh", icon("refresh"), class = "btn-primary")
#tags$b(textOutput("bond"))
#tags$br()
```

[Learn more](https://www.nsandi.com/products/premium-bonds/) about premium bonds

[See my Shiny apps](https://drclongstaff.github.io/shiny-clots/) for reproducible analysis of biochemical assays

[Contact me](mailto:%20drclongstaff@gmail.com, "drclongstaff@gmail.com") for issues or comments about the dashboard. Or tell me if you have reclaimed a prize!

# Premium bond monthly prize draws began in 1956 and there are millions of unclaimed prizes

```{r}
#| context: server
#monthly draws
yearRes <- reactive({data.frame(t(sapply(allMonths, function(x) Earnest(input$bondStake, prizePool, prizeVal, prizeProb))))
colnames(yearRes)[c(1,2,3,4)] <- c("Number_prizes", "Prize_value", "Annual_yield", "Prizes")

#add a summary row to the table
totalsRow <- data.frame(
  Number_prizes      = sum(as.numeric(yearRes$Number_prizes)),
  Prize_value  = sum(as.numeric(yearRes$Prize_value)), 
  Annual_yield = 100*(sum(as.numeric(yearRes$Prize_value))/bondStake),
  Prizes = " "
  #Prizes = paste(sort(unlist(strsplit(yearRes$Prizes, ", "))), collapse = ", ")
  
)

yearRes <- rbind(yearRes, totalsRow)
rownames(yearRes)[nrow(yearRes)] <- "Total"

})

#Long term results
lifeRes <- reactive({
  ResLife <- sapply(1:input$simYrs, function(x) earnYear(bondStake, prizePool, prizeVal, prizeProb))
  ResLife <- sort(ResLife, decreasing = TRUE)
})

```

## Row {height="14%"}

```{r}
#| content: valuebox
#| title: "There is £108,147,675 available"
#| color: pink
#| icon: currency-pound
p("from 2,608,195 unclaimed prizes")
```

```{r}
#| content: valuebox
#| title: "This dashboard locates unclaimed prizes"
#| color: blue
#| icon: unlock-fill
p("simply enter premium bond numbers top-left")
```

## Row {height="86%" .fill}

### Table

```{r}
#Summary table of data
prizeVal <- c(1e6, 100000, 50000, 25000, 10000, 5000, 1000, 500, 100, 50, 25)
prizeNos <- c(2,71,142,255,712,1421,15021, 45063, 1535556, 1535556, 2803175)
allPrizes <- sum(prizeNos)
prizeProb <- prizeNos/allPrizes
probTab <- data.frame("Prize"=LETTERS[1:11],
                      "Value"=prizeVal,
                      "Number"=prizeNos,
                      "Probability"=signif(prizeProb,3)
)

summaryRow <- data.frame("Prize"="Totals", "Value"= sum(prizeVal), "Number"=allPrizes, "Probability" = round(sum(prizeProb)))

summaryTab <- rbind(probTab, summaryRow)

summaryTab |> gt() |> 
  #cols_label(Prize ~ "Prize Value", Number ~ "Number of Prizes", Total_value ~ "Total Value") |> 
  tab_header(title = "Expected prizes") |> 
  opt_stylize(style = 6, color = "pink") |> 
  opt_table_font(stack = "humanist") #|> 
  #tab_footnote(
    #footnote = "There are 2,608,195 unclaimed prizes totalling £108,147,675"
    
  #)
  
```


### Table2

```{r}
yearRes() |> gt() |> 
  #cols_label(Prize ~ "Prize Value", Number ~ "Number of Prizes", Total_value ~ "Total Value") |> 
  tab_header(title = "Expected prizes") |> 
  opt_stylize(style = 6, color = "pink") |> 
  opt_table_font(stack = "humanist")
```



### Column {.tabset}

#### Analysed

```{r}
# #| title: Number of unclaimed prizes by value are ~linear on a log-log plot
lifeRes <- lifeRes()
mySeq <- 3
forText <- simyrs/8
meanResAll <- mean(lifeRes)
meanResYield <- round((100*meanResAll/input$bondStake),2)
ggplot() + aes(lifeRes)+
  geom_histogram(binwidth = 0.075, fill="steelblue", col = "white")+
  scale_x_continuous(trans='log10')+
  geom_vline(xintercept = meanResAll, col = "pink", lwd = 1, lty = "dashed")+
  #geom_vline(xintercept = logmean, col = "red", lwd = 1, lty = "dashed")+
  annotate("text", x = lifeRes[1:mySeq], y=seq(1, mySeq, 1)*forText*0.25, label = lifeRes[1:mySeq])+
  #annotate("text", x=logmean, y=-10, label= meanRes)+
  annotate("text", x=meanResAll, y=-forText*0.1, label= meanResAll)+
  annotate("text", x=meanResAll, y=-forText*0.2, label= meanResYield)+
  theme_minimal()
```

#### Raw data

The text file provided by NS&I is not easy to search



#### Cleaning code


